# Generated by Django 6.0.5 on 2026-05-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Nama file asli yang diupload', max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hash dari file asli', max_length=64, unique=True)),
                ('merkle_root', models.CharField(help_text='Akar Merkle Tree', max_length=64)),
                ('block_index', models.IntegerField(help_text='Posisi blok di dalam rantai Blockchain')),
                ('prev_hash', models.CharField(help_text='Hash dari blok sebelumnya', max_length=64)),
                ('ciphertext_path', models.CharField(help_text='Lokasi file .bin yang sudah dienkripsi', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
