# Generated by Django 6.0.5 on 2026-05-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedocument',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Ukuran file dalam bytes', null=True),
        ),
        migrations.AddField(
            model_name='securedocument',
            name='status_verifikasi',
            field=models.CharField(choices=[('VALID', 'Valid'), ('CORRUPTED', 'Corrupted'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
