# Generated by Django 6.0.5 on 2026-06-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0002_securedocument_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedocument',
            name='hash_algo',
            field=models.CharField(choices=[('SHA256', 'SHA-256'), ('SHA3_256', 'SHA-3 (Keccak-256)')], default='SHA256', max_length=15),
        ),
        migrations.AlterField(
            model_name='securedocument',
            name='file_hash',
            field=models.CharField(help_text='Hash dari file asli', max_length=64, unique=True),
        ),
    ]
